name: Berry
main: hydroboat-studios\Berry
version: 1.0.0-beta1
api:
  - 3.0.0

# Extra
author: HydroBoatStudios
description: A PMMP plugin that aims to enhance vanilla PocketMine-MP!
website: https://github.com/hydroboat-studios/Berry
